version: '3'

services:
  web:
    restart: always
    command: python3 app.py
    tty: true
    build:
      context: .
    expose:
      - 5000
    volumes:
      - .:/app:Z

  nginx:
    image: django_template
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
